import type { pluginsZh } from "../zh/plugins.ts";

export const pluginsEn: Record<keyof typeof pluginsZh, string> = {
 "plugins.reviewAgain": "Review a New Request", "plugins.reviewAgainHint": "Review a new request? The previous request may have committed and remains in the operation history. This does not undo it.",
 "plugins.reviewUpgrade": "I reviewed this version's capabilities, commands, credential uses and project scope", "plugins.reviewRequired": "Review and acknowledge the changes before enabling this version.", "plugins.versionChanges": "Version change: {before} → {after}", "plugins.contentChanged": "The content digest changed; skill files may have changed too. Manifest differences appear below. Inspect package contents to review execution and configuration details.",
 "plugins.managedResources": "Capabilities from Plugins", "plugins.managedHint": "Manage versions, project scope and machines through the package installation.",
 "plugins.adoptAgent": "Adopt This Existing Agent", "plugins.adoptHint": "Keep this agent's model, options and instructions. Choose legacy attachments to replace with package capabilities. Source skill directories and machine MCP definitions remain available to other agents.", "plugins.keepAttachment": "Keep Existing Attachment", "plugins.replacedAttachments": "Replace {skills} skill attachments and {tools} MCP attachments. This agent will no longer assemble both copies.",
 "plugins.inspect": "Inspect Package Contents", "plugins.credentialReference": "Node Credential Reference", "plugins.imported": "Package imported. Configure its projects and machines next.",
 "plugins.usage": "Session References & Removal", "plugins.usageHint": "Idle and archived sessions may retain older versions. Close their native sessions before removing unused runtime content.", "plugins.closeRuntime": "Close & Release Session", "plugins.confirmCloseRuntime": "Close this runtime and release its native session restore entry? Conversation history is kept. Active tasks will block closing.", "plugins.inUse": "In Use", "plugins.retained": "Retained", "plugins.noReferences": "No retained session references.", "plugins.remove": "Remove Installation", "plugins.removeHint": "Stop new bindings first. Removal requires every machine to be verifiable, all session references released and all processes confirmed stopped. Package-library versions remain available for future installation.", "plugins.confirmRemove": "Remove this installation and its unreferenced runtime directories? Package-library versions and conversation history are kept.", "plugins.removed": "Installation removed.",
    "nav.plugins": "Plugins", "plugins.title": "Plugins", "plugins.description": "Package skills, tools and agent presets for use across projects and machines.",
    "plugins.import": "Import Package", "plugins.refresh": "Refresh Status", "plugins.library": "Package Library", "plugins.installations": "Installations & Scope",
    "plugins.installationsHint": "Enabling selects a version for new sessions. Machine preparation is shown separately.", "plugins.empty": "No Capability Packages", "plugins.emptyHint": "Import a local package or a fixed Git commit, review its contents, then choose projects and machines.",
    "plugins.noInstallations": "Choose an imported package to configure its projects and target machines.", "plugins.configure": "Configure Installation", "plugins.edit": "Edit Configuration", "plugins.prepare": "Prepare Machines", "plugins.enable": "Enable for New Sessions", "plugins.disable": "Stop New Bindings",
    "plugins.enabled": "Enabled", "plugins.disabled": "Not Enabled", "plugins.version": "Version", "plugins.projects": "Projects", "plugins.machines": "Target Machines", "plugins.local": "This Machine",
    "plugins.pending": "Pending", "plugins.prepared": "Prepared", "plugins.offline": "Offline", "plugins.unavailable": "Needs Attention", "plugins.package": "Package", "plugins.digest": "Content Digest", "plugins.skills": "Skills", "plugins.tools": "MCP Tools", "plugins.presets": "Agent Presets",
    "plugins.source": "Source", "plugins.directory": "Local Package Directory", "plugins.git": "Fixed Git Commit", "plugins.location": "Directory or Repository URL", "plugins.commit": "Full Commit ID", "plugins.subdir": "Package Subdirectory (Optional)",
    "plugins.preview": "Preview Contents", "plugins.importProject": "Import into Project", "plugins.importConfirm": "Confirm Import", "plugins.previewHint": "Import stores the reviewed content. Configure and enable it before new sessions can use it.",
    "plugins.sourceHint": "The directory is on the coordinator. Git accepts an absolute local path or HTTPS URL with a full commit ID.", "plugins.selectProject": "Choose a project…", "plugins.selectNode": "Choose a machine…", "plugins.selectSecret": "Choose a node-local credential reference…",
    "plugins.installationId": "Installation Name", "plugins.installationHint": "Lowercase letters, digits, dots, underscores and hyphens, for example github-review.", "plugins.configuration": "Machine Configuration", "plugins.settingsHint": "Public settings can be shared. Select credential references here; credential values stay on the machine.",
    "plugins.secretHint": "Configure credentials on the target machine with secret-put, then refresh the references.", "plugins.noSecrets": "No credential references are available on this machine.", "plugins.noSettings": "This package needs no additional settings.", "plugins.save": "Save Installation", "plugins.saved": "Installation saved. Prepare the machines and enable it for new sessions.",
    "plugins.selectRequired": "Choose at least one project and one machine.", "plugins.required": "Complete required settings and choose credential references.", "plugins.unsaved": "Discard your unsaved changes?", "plugins.confirmDisable": "Stop new plugin bindings? Existing sessions will keep their original version.", "plugins.confirmEnable": "Enable this version for the selected projects and machines? Existing sessions will keep their original version.",
    "plugins.operations": "Recent Operations", "plugins.operationsHint": "Retries keep the original command identity and request content.", "plugins.createAgent": "Use Agent Preset", "plugins.agentId": "Agent Name", "plugins.preset": "Preset", "plugins.model": "Model Preference (Optional Override)", "plugins.instructions": "Instructions (Optional Override)",
    "plugins.previewAgent": "Preview Agent", "plugins.applyAgent": "Save Agent", "plugins.agentSaved": "Agent saved. Select it in the workbench.", "plugins.preserved": "Preserved user changes: {fields}", "plugins.existingAgent": "This updates an existing preset agent while preserving user changes.", "plugins.harness": "AI Tool", "plugins.close": "Close Plugin Details", "plugins.retry": "Retry Original Request", "plugins.couldNotLoad": "Current plugin state is unavailable. Refresh before making changes.", "plugins.versionHint": "Choose an imported version to upgrade or roll back. Existing sessions remain pinned.",
};
