import type { sideChatZh } from "../zh/side-chat.ts";

export const sideChatEn = {
    "sideChat.originAgentUnavailable": "The original conversation’s agent could not be verified as usable for this project. Nothing was sent. Choose an available agent in the workbench.",
    "sideChat.agentSelectionUnconfirmed": "Agent selection is unconfirmed. Nothing was sent; retry checks the same selection.",
    "sideChat.chooseAgent": "Choose an available agent for this side chat in the workbench. Send there, or return here to verify the choice and continue.",
    "sideChat.checkChosenAgent": "Verify workbench selection",
    "sideChat.queued": "Queued", "sideChat.materialCount": "{count} referenced materials",
    "sideChat.title": "Side chat", "sideChat.region": "Selection side chat", "sideChat.close": "Close side chat", "sideChat.openMain": "Open in workbench", "sideChat.source": "Selected material", "sideChat.added": "Selection added to the draft. The agent is asked only when you send.", "sideChat.empty": "Discuss this selection without replacing the original conversation.", "sideChat.message": "Side chat message", "sideChat.placeholder": "What would you like to ask about this…", "sideChat.send": "Send", "sideChat.queue": "Queue", "sideChat.stop": "Stop", "sideChat.stopping": "Stopping…", "sideChat.binding": "Preparing the project conversation…", "sideChat.sending": "Sending…", "sideChat.running": "The agent is working…", "sideChat.loading": "Loading side chat…", "sideChat.retry": "Retry", "sideChat.retrySend": "Retry this submission", "sideChat.confirmed": "Confirmed received", "sideChat.unknown": "Delivery is not confirmed. Retry preserves this submission and its references.", "sideChat.conflict": "Submission identity conflicts. Check the side chat record first.", "sideChat.rejected": "Submission was rejected. Your draft is retained.", "sideChat.storage": "The side chat draft could not be saved. Check browser storage and retry.", "sideChat.unavailable": "This Hub does not support safe side chat submission. Update it and retry.", "sideChat.projectChanged": "The side chat project binding changed. Nothing was sent; check it in the workbench.", "sideChat.boundFailed": "The side chat could not bind to the original project. Nothing was sent.", "sideChat.invalidSource": "The material and selection reference do not match.", "sideChat.stopUnknown": "Stop is not confirmed. Retry the same stop request.", "sideChat.stopped": "Stop request handled", "sideChat.removeRef": "Remove {title}", "sideChat.restore": "Restore draft"
} as const satisfies Record<keyof typeof sideChatZh, string>;
