// Source preview only; every API is intercepted, no live hub and no dist build.
import assert from "node:assert/strict";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "../../web/console/node_modules/vite/dist/node/index.js";
import { chromium } from "../../web/console/node_modules/playwright/index.mjs";
const web = fileURLToPath(new URL("../../web/console", import.meta.url));
const server = await createServer({ configFile: path.join(web, "vite.config.ts"), root: web, server: { host: "127.0.0.1", port: 0 } });
await server.listen();
const url = server.resolvedUrls.local[0];
const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL });
const A="console:material-ui", at="2026-09-07T01:00:00Z", base="a".repeat(40), after="b".repeat(40);
const png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO7+gxkAAAAASUVORK5CYII=","base64");
const context=await browser.newContext({viewport:{width:1600,height:1000},serviceWorkers:"block"});const page=await context.newPage();page.setDefaultTimeout(7000);
const f={version:"test",supportsMaterials:true,captures:[],posts:[],queue:[],materials:new Map(),notes:[],answers:[],questions:[],hideQueue:false,reset:false,errors:[]};
page.on("pageerror",e=>f.errors.push(String(e)));
function material(id,title,source,kind="text",mime="text/plain",data=Buffer.from("first\nsecond\nthird\n")) {const value={id,project:"p",title,source,kind,mime,size:data.length,digest:"d".repeat(64),created_at:at,...(kind==="image"?{width:1,height:1}:{})};f.materials.set(id,{value,data});return value;}
await page.route("**/*",async route=>{
 const req=route.request(),u=new URL(req.url()),p=u.pathname;
 if(u.origin!==new URL(url).origin){f.errors.push("external "+u.origin);return route.abort();}
 if(!p.startsWith("/console/")&&!['/state','/events'].includes(p))return route.continue();
 const input=req.method()==="GET"?null:(req.headers()['content-type']||'').includes('application/json')?req.postDataJSON():null;
 if (p === "/console/coordination") return route.fulfill({ json: { enabled: false, nodes: [], events: [], epoch: 0, revision: 0, authoritative: false, observed_at: "", auto_failover: false, ready: false } });
 if(p==="/console/desktop")return route.fulfill({json:{enabled:false,setup_required:false,agent_count:0}});
 if(p==="/state")return route.fulfill({json:{at,hub:{node:"test-hub",version:f.version},nodes:[],agents:[],projects:[{id:"p",node:"test-hub",path:"/work/p",repo:"inplace",level:"public",agents:[],workspaces:[]}],tasks:[{id:"11",channel:A,project_id:"p",goal:"Code task",state:"running",lifecycle:"running",execution:"idle",lane:"pending",attention:0,turns:1,max_turns:10,updated_at:at}],plans:[],attempts:[],landings:[]}});
 if(p==="/console/context")return route.fulfill({json:{enabled:true,context:{conversation:A,project:{id:"p",node:"test-hub",path:"/work/p",repo:"inplace",level:"public",bound:true},agents:[]}}});
 if(p==="/console/replies")return route.fulfill({json:{enabled:true,replies:[{id:"r1",conversation:A,kind:"reply",at,text:"Reference reply",project_id:"p",revision:"reply-version-1"}]}});
 if(p==="/console/conversations")return route.fulfill({json:{conversations:[{id:A,title:"Material conversation",project:"p",count:1,last_at:at,running:false}]}});
 if(p==="/console/verbs")return route.fulfill({json:{verbs:[]}});
 if(p==="/console/suggest")return route.fulfill({json:{suggestions:[]}});
 if(p==="/console/queue"){
  if(req.method()==="POST"){f.posts.push(input);let item=f.queue.find(e=>e.key==="client:"+input.command_id);if(!item){item={id:"e"+(f.queue.length+1),conversation:input.conversation,key:"client:"+input.command_id,input:input.input,refs:input.refs,locale:input.locale,quotes:input.quotes,state:"queued",enqueued_at:at};f.queue.push(item);}if(f.reset){f.reset=false;return route.abort('connectionreset');}return route.fulfill({json:item});}
  return route.fulfill({json:{queue:f.hideQueue?[]:f.queue,submission_keys:true,material_refs:f.supportsMaterials,interactive_requests:true}});
 }
 if(p==="/console/materials/capture"){f.captures.push(input);assert.equal(input.project,"p");if(input.source.kind==="reply")assert.equal(input.source.revision,"reply-version-1");return route.fulfill({json:material("m-"+f.captures.length,input.title||input.source.path||"Reference reply",input.source)});}
 if(p==="/console/materials/upload"){const kind=req.headers()['content-type'].startsWith('image/')?'image':'binary';return route.fulfill({json:material("m-upload-"+f.materials.size,u.searchParams.get('name'),{kind:'upload'},kind,req.headers()['content-type'],req.postDataBuffer())});}
 if(p.match(/^\/console\/materials\/[^/]+\/content$/)){const m=f.materials.get(p.split('/')[3]);return route.fulfill({contentType:m.value.mime,body:m.data});}
 if(p.match(/^\/console\/materials\/[^/]+$/)){const m=f.materials.get(p.split('/')[3]);return route.fulfill({json:m.value});}
 if(p==="/console/annotations")return route.fulfill({json:{annotations:f.notes.filter(n=>!n.deleted)}});
 if(p.startsWith('/console/annotations/')){const id=p.split('/')[3],old=f.notes.find(n=>n.id===id);if((old?.revision||0)!==input.expected_revision)return route.fulfill({status:409,json:{error:'Annotation changed'}});const note={...input,id,author:'owner',revision:(old?.revision||0)+1,created_at:at,updated_at:at};f.notes=f.notes.filter(n=>n.id!==id);f.notes.push(note);return route.fulfill({json:note});}
 if(p==="/console/questions")return route.fulfill({json:{questions:f.questions}});
 if(p.match(/^\/console\/questions\/[^/]+\/answer$/)){f.answers.push(input);if(input.decision!=='accept'&&input.choice)return route.fulfill({status:400,json:{error:'Non-accept decision must not include choice'}});await new Promise(r=>setTimeout(r,150));const q=f.questions.find(q=>q.id===p.split('/')[3]);q.state=input.decision==='accept'?'answered':input.decision==='decline'?'declined':'cancelled';q.answer=input;return route.fulfill({json:{question:q}});}
 if(p==="/console/tasks/11/attempts")return route.fulfill({json:[{id:'attempt1',kind:'task',state:'done',base,artifact:after,started_at:at,files:1}]});
 if(p==="/console/attempts/attempt1/changes")return route.fulfill({json:{attempt:'attempt1',project:'p',base,artifact:after,changes:[{path:'app.ts',status:'M',added:2,deleted:1}]}});
 if(p==="/console/attempts/attempt1/tree")return route.fulfill({json:{attempt:'attempt1',commit:after,which:'result',dir:'',entries:[{name:'app.ts',path:'app.ts',kind:'file',size:20}]}});
 if(p==="/console/attempts/attempt1/file")return route.fulfill({json:{attempt:'attempt1',commit:after,path:'app.ts',text:'first\nsecond\nthird\n',size:20}});
 if(p==="/console/attempts/attempt1/diff")return route.fulfill({json:{path:'app.ts',diff:'--- a/app.ts\n+++ b/app.ts\n@@ -1,2 +1,3 @@\n-old\n+first\n+second\n third\n'}});
 f.errors.push(req.method()+" "+p);return route.fulfill({status:500,json:{error:'Unmocked API'}});
});
await page.addInitScript((conversation)=>{sessionStorage.setItem('steve.conversation',conversation);localStorage.setItem('steve.ui.locale','en');window.sources=[];window.EventSource=class{constructor(){window.sources.push(this);setTimeout(()=>this.onopen?.(),0)}close(){window.sources=window.sources.filter(s=>s!==this)}};window.emit=(e)=>window.sources.forEach(s=>s.onmessage?.({data:JSON.stringify(e)}));},A);
async function waitFor(test,label){for(let i=0;i<100;i++){if(await test())return;await new Promise(r=>setTimeout(r,30));}assert.fail(label);}
try{
 await page.goto(url+'#/console');await page.getByRole('heading',{name:'Material conversation',exact:true}).waitFor();await page.getByRole('button',{name:'Actions',exact:true}).waitFor();
 await page.getByRole('button',{name:'Actions',exact:true}).click();await page.getByRole('menuitem',{name:'Add to Material conversation',exact:true}).click();await page.getByRole('list',{name:'Attached materials'}).getByText('Reference reply').waitFor();assert.equal(f.posts.length,0);
 await page.getByRole('button',{name:'Actions',exact:true}).click();await page.getByRole('menuitem',{name:'Add to side',exact:true}).click();await page.getByRole('tab',{name:'Materials',exact:true}).waitFor();assert.equal(f.posts.length,0);
 await page.getByRole('button',{name:'Actions',exact:true}).click();await page.getByRole('menuitem',{name:'Annotate',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Annotate material'});await dialog.getByRole('textbox',{name:'Annotation',exact:true}).fill('Verify the result');await dialog.getByRole('button',{name:'Save',exact:true}).click();await waitFor(()=>f.notes.length===1,'annotation persisted');await dialog.waitFor({state:'hidden'});await page.getByText('Verify the result',{exact:true}).waitFor();assert.equal(f.notes.length,1);assert.equal(f.posts.length,0);console.log('PASS reply capture, explicit draft target, local pin and durable annotation');
 // Source and deleted-side line ranges use different immutable commits.
 await page.getByRole('tab',{name:'Code',exact:true}).click();await page.getByRole('button',{name:/^(浏览文件|Browse files)$/}).click();await page.getByRole('button',{name:'app.ts',exact:true}).first().click();
 const source=page.getByRole('region',{name:'app.ts file content'});await source.getByRole('button',{name:'Select line 2',exact:true}).click();await source.getByRole('button',{name:'Select line 3',exact:true}).click({modifiers:['Shift']});
 await page.getByRole('region',{name:'Source app.ts',exact:true}).getByRole('button',{name:'Actions',exact:true}).click();await page.getByRole('menuitem',{name:'Add to Material conversation',exact:true}).click();
 await waitFor(()=>f.captures.at(-1)?.source.commit===after,'source snapshot capture');assert.equal(f.captures.at(-1).source.commit,after);
 await page.getByRole('button',{name:'Diff',exact:true}).click();await page.getByRole('button',{name:'Before · Select line 1',exact:true}).click();await page.locator('.review-diff').getByRole('button',{name:'Actions',exact:true}).click();await page.getByRole('menuitem',{name:'Add to Material conversation',exact:true}).click();await waitFor(()=>f.captures.at(-1)?.source.commit===base,'base snapshot capture');assert.equal(f.captures.at(-1).source.commit,base);
 await page.getByRole('button',{name:'Back',exact:true}).click();const draft=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('steve.console.drafts')));assert.ok(draft.materials[A].some(r=>r.selector?.start===2&&r.selector?.end===3));assert.ok(draft.materials[A].some(r=>r.selector?.start===1&&r.selector?.end===1));console.log('PASS source range and deleted diff range anchor exact snapshots');
 await page.getByRole('button',{name:'Hide details',exact:true}).click();
 await page.getByLabel('Attach files',{exact:true}).setInputFiles([{name:'pixel.png',mimeType:'image/png',buffer:png},{name:'notes.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 fixture')}]);await page.getByRole('list',{name:'Attached materials'}).getByText('notes.pdf',{exact:true}).waitFor();
 const imageChip=page.getByRole('list',{name:'Attached materials'}).getByText('pixel.png',{exact:true});await imageChip.click();const imageDialog=page.getByRole('dialog',{name:'Preview',exact:true});await imageDialog.getByRole('img').waitFor();await imageDialog.getByText('Image region',{exact:true}).click();const x=imageDialog.getByRole('textbox',{name:'Left ratio',exact:true});await x.fill('');await x.pressSequentially('0.25');assert.equal(await x.inputValue(),'0.25');await imageDialog.getByRole('textbox',{name:'Width ratio',exact:true}).fill('0.5');await imageDialog.getByRole('textbox',{name:'Height ratio',exact:true}).fill('0.5');await imageDialog.getByRole('button',{name:'Use region',exact:true}).click();await imageDialog.getByText('Selected original image region: x=0.25, y=0, width=0.5, height=0.5',{exact:true}).waitFor();
 await x.fill('NaN');await imageDialog.getByRole('button',{name:'Use region',exact:true}).click();await imageDialog.getByRole('alert').waitFor();assert.equal(await x.inputValue(),'NaN');await x.fill('0.9');await imageDialog.getByRole('button',{name:'Use region',exact:true}).click();await imageDialog.getByRole('alert').waitFor();await x.fill('0.25');await page.setViewportSize({width:390,height:844});await imageDialog.getByRole('button',{name:'Use region',exact:true}).click();await imageDialog.getByRole('button',{name:'Actions',exact:true}).click();await page.getByRole('menuitem',{name:'Add to Material conversation',exact:true}).click();await imageDialog.getByRole('button',{name:'Close',exact:true}).click();const crop=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('steve.console.drafts')).materials['console:material-ui'].find(r=>r.selector?.kind==='rect'));assert.deepEqual(crop.selector.rect,{x:0.25,y:0,width:0.5,height:0.5});await page.setViewportSize({width:1600,height:1000});console.log('PASS image region raw decimals, NaN/bounds rejection and scale-independent normalized coordinates');
 f.hideQueue=true;f.reset=true;await page.getByRole('textbox',{name:'Message',exact:true}).fill('Use these exact references');await page.getByRole('textbox',{name:'Message',exact:true}).press('Enter');await page.getByRole('button',{name:'Retry this submission',exact:true}).waitFor();const first=f.posts[0];assert.equal(first.locale,'en');assert.equal(first.refs.length,6);await page.getByRole('button',{name:'Retry this submission',exact:true}).click();await waitFor(()=>f.posts.length===2,'retry');assert.equal(f.queue.length,1);assert.equal(f.posts[1].command_id,first.command_id);assert.deepEqual(f.posts[1].refs,first.refs);console.log('PASS attachments persist with immutable refs and retry identity');
 // Previously attached materials must not be silently dropped by an older Hub.
 await page.getByLabel('Attach files',{exact:true}).setInputFiles({name:'old-hub.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 older hub')});await page.getByRole('list',{name:'Attached materials'}).getByText('old-hub.pdf',{exact:true}).waitFor();
 f.supportsMaterials=false;await page.getByRole('textbox',{name:'Message',exact:true}).fill('Do not send without attachment');await page.getByRole('textbox',{name:'Message',exact:true}).press('Enter');await waitFor(async()=>await page.getByRole('textbox',{name:'Message',exact:true}).inputValue()==='Do not send without attachment','material capability rejection keeps draft');assert.equal(f.posts.length,2);f.supportsMaterials=true;
 console.log('PASS missing material capability prevents POST rather than stripping refs');

 f.questions=[{id:'q1',conversation:A,exchange_id:'e1',kind:'question',title:'Choose a target',message:'Where should the change apply?',options:[{id:'yes',label:'Only this project'},{id:'no',label:'Do not proceed'}],required:true,created_at:at,deadline:'2030-01-01T00:00:00Z',updated_at:at,state:'pending'}];await page.evaluate(e=>window.emit(e),{kind:'console.question',conversation:A,text:'q1',at});await page.getByRole('button',{name:'Only this project',exact:true}).click();await page.getByText('1 recent resolved requests',{exact:true}).waitFor();await page.getByText('1 recent resolved requests',{exact:true}).click();await page.getByText('Answered',{exact:true}).waitFor();assert.equal(f.answers.length,1);assert.equal(f.answers[0].choice,'yes');assert.equal(f.posts.length,2);console.log('PASS agent question uses original options without submitting another prompt');
 for(const [decision,label] of [['decline','Decline'],['cancel','Cancel request']]) {const id='q-'+decision;f.questions=[{id,conversation:A,exchange_id:'e1',kind:'permission',title:id,message:'Choose before declining or cancelling',options:[{id:'allow_once',label:'Allow only once'}],required:true,created_at:at,deadline:'2030-01-01T00:00:00Z',updated_at:at,state:'pending'}];await page.evaluate(e=>window.emit(e),{kind:'console.question',conversation:A,text:id,at});await page.getByText('Allow only once',{exact:true}).click();const before=f.answers.length;await page.getByRole('button',{name:label,exact:true}).click();await waitFor(()=>f.questions[0].state!=='pending','decision accepted');assert.equal(f.answers.length,before+1);assert.equal(f.answers.at(-1).decision,decision);assert.equal(Object.hasOwn(f.answers.at(-1),'choice'),false);}
 console.log('PASS selected permission can be declined or cancelled with one valid decision payload');
 // A Hub upgrade must not discard edits outside the composer.
 await page.getByRole('textbox',{name:'Message',exact:true}).fill('');let navigations=0;const navigated=frame=>{if(frame===page.mainFrame())navigations++;};page.on('framenavigated',navigated);
 await page.getByRole('button',{name:'Actions',exact:true}).click();await page.getByRole('menuitem',{name:'Annotate',exact:true}).click();const editing=page.getByRole('dialog',{name:'Annotate material',exact:true});await editing.getByRole('textbox',{name:'Annotation',exact:true}).fill('Unsaved annotation survives an upgrade');f.version='test-upgraded';await page.evaluate(e=>window.emit(e),{kind:'node.updated',at});await waitFor(async()=> (await page.locator('.console-main').textContent()).includes('Coordinator updated.'),'upgrade banner');assert.equal(navigations,0);assert.equal(await editing.getByRole('textbox',{name:'Annotation',exact:true}).inputValue(),'Unsaved annotation survives an upgrade');assert.equal(await page.evaluate(()=>{const event=new Event('beforeunload',{cancelable:true});window.dispatchEvent(event);return event.defaultPrevented;}),true);
 page.once('dialog',dialog=>dialog.dismiss());await editing.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await editing.isVisible(),true);page.once('dialog',dialog=>dialog.accept());await editing.getByRole('button',{name:'Cancel',exact:true}).click();await editing.waitFor({state:'hidden'});page.off('framenavigated',navigated);console.log('PASS Hub upgrades preserve annotation drafts and annotation dismissal has a local edit guard');
 const makeQuestion=(id,state,time)=>({id,conversation:A,exchange_id:'e1',kind:'question',title:id,message:'A retained question with enough context to wrap in a small window.',options:[],allow_free_text:true,required:true,created_at:time,deadline:'2030-01-01T00:00:00Z',updated_at:time,state});
 f.questions=[...Array.from({length:24},(_,i)=>makeQuestion('history-'+i,'answered',new Date(Date.parse(at)+i*1000).toISOString())),makeQuestion('pending-later','pending','2026-09-07T03:00:00Z'),makeQuestion('pending-first','pending','2026-09-07T02:00:00Z')];
 await page.evaluate(e=>window.emit(e),{kind:'console.question',conversation:A,text:'pending-first',at});await page.getByRole('heading',{name:'pending-first',exact:true}).waitFor();
 const panel=page.getByRole('region',{name:'Your response is needed'});assert.equal(await panel.locator(':scope > article h3').first().innerText(),'pending-first');assert.equal(await panel.locator('details article').count(),5);await page.setViewportSize({width:390,height:844});
 const message=page.getByRole('textbox',{name:'Message',exact:true});await waitFor(async()=>{const box=await message.boundingBox();return box&&box.y>=0&&box.y+box.height<=844;},'Question history must not push the composer out of the viewport after responsive layout settles');
 await panel.getByRole('textbox',{name:'Answer',exact:true}).first().fill('Narrow-screen response');assert.equal(await panel.getByRole('textbox',{name:'Answer',exact:true}).first().inputValue(),'Narrow-screen response');assert.ok(await panel.evaluate(el=>el.clientHeight<=window.innerHeight*.4+1));console.log('PASS many questions keep pending order, bound history and preserve a reachable mobile composer');

 assert.deepEqual(f.errors,[]);
}catch(error){console.log("DEBUG",JSON.stringify(f.errors),JSON.stringify(f.captures),await page.locator("body").innerText());throw error;}finally{await context.close();await browser.close();await server.close();}
