// Isolated source harness. Does not import App or build embedded assets.
import assert from 'node:assert/strict';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createServer} from '../../web/console/node_modules/vite/dist/node/index.js';
import {chromium} from '../../web/console/node_modules/playwright/index.mjs';
const web=fileURLToPath(new URL('../../web/console',import.meta.url));
const harness=`import React from 'react';import{createRoot}from'react-dom/client';import{LocaleProvider,useI18n}from'/src/providers/locale-provider';import{FleetProvider}from'/src/lib/fleet';import{MaterialProvider}from'/src/providers/material-provider';import{SideChatProvider,useSideChat}from'/src/providers/side-chat-provider';import{SideChatPanel}from'/src/components/steve/side-chat';import{useDraft,updateDraft}from'/src/lib/drafts';import{Dialog,Modal,ModalOverlay}from'react-aria-components';import '/src/styles/globals.css';function Harness(){const side=useSideChat();const[review,setReview]=React.useState(false);const{setLocale}=useI18n();const text=useDraft('console:main');const open=(project,id)=>side.open({material:{id,project,title:id,kind:'text',mime:'text/plain',size:8,digest:'d'.repeat(64),source:{kind:'reply',conversation:'console:main',reply_id:'r1',revision:'v1'},created_at:'2026-09-07T00:00:00Z'},ref:{id,selector:{kind:'quote',quote:'selected'}},excerpt:'selected',originConversation:'console:origin-'+project});return <><textarea aria-label="Main draft" value={text} onChange={e=>updateDraft('console:main',e.target.value)}/><p>Original conversation response</p><button onClick={()=>open('p','material-a')}>Open A</button><button onClick={()=>open('p','material-b')}>Add B</button><button onClick={()=>open('q','material-q')}>Open Q</button><button onClick={()=>open('restart','material-restart')}>Open restart</button><button onClick={()=>open('unavailable','material-unavailable')}>Open unavailable</button><button onClick={()=>open('constructor','material-constructor')}>Open constructor</button><button onClick={()=>open('__proto__','material-proto')}>Open __proto__</button><button onClick={()=>setReview(true)}>Move to review</button><button onClick={()=>setLocale('zh')}>Chinese</button><button onClick={()=>setLocale('en')}>English</button><div style={{height:650,width:390}}>{!review&&<SideChatPanel/>}</div>{review&&<ModalOverlay isOpen style={{position:'fixed',inset:0,background:'#fff',zIndex:100}}><Modal><Dialog aria-label="Review host"><button onClick={()=>setReview(false)}>Return to console host</button><div style={{height:650,width:390}}><SideChatPanel/></div></Dialog></Modal></ModalOverlay>}</>};createRoot(document.getElementById('root')).render(<LocaleProvider><FleetProvider><MaterialProvider><SideChatProvider><Harness/></SideChatProvider></MaterialProvider></FleetProvider></LocaleProvider>);`;
const server=await createServer({configFile:path.join(web,'vite.config.ts'),root:web,plugins:[{name:'side-chat-harness',resolveId(id){if(id==='/__side-harness.tsx')return id;},load(id){if(id==='/__side-harness.tsx')return harness;},configureServer(server){server.middlewares.use((req,res,next)=>{if(req.url?.startsWith('/__side-harness.html')){res.setHeader('Content-Type','text/html');void server.transformIndexHtml('/__side-harness.html','<div id="root"></div><script type="module" src="/__side-harness.tsx"></script>').then(html=>res.end(html));}else next();});}}],server:{host:'127.0.0.1',port:0}});await server.listen();const url=server.resolvedUrls.local[0];const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL});const context=await browser.newContext({viewport:{width:1200,height:1000},serviceWorkers:'block'});let page=await context.newPage();page.setDefaultTimeout(7000);
const gate=()=>{let release;const promise=new Promise(r=>release=r);return{promise,release}};
const f={replyReads:0,queueReads:0,agentSelect:[],selected:{},originUsable:true,resetAgent:false,send:[],post:[],queue:[],replies:{},bound:{},bindGate:gate(),reset:true,resetBinding:false,hideQueue:true,errors:[]};const at='2026-09-07T01:00:00Z';
page.on('pageerror',e=>f.errors.push(String(e)));await context.addInitScript(()=>{localStorage.setItem('steve.ui.locale','en');sessionStorage.setItem('steve.conversation','console:main');window.sources=[];window.EventSource=class{constructor(){window.sources.push(this);setTimeout(()=>this.onopen?.(),0)}close(){window.sources=window.sources.filter(s=>s!==this)}};window.emit=e=>window.sources.forEach(s=>s.onmessage?.({data:JSON.stringify(e)}));});
await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url()),p=u.pathname;if(u.origin!==new URL(url).origin){f.errors.push('external request');return route.abort();}if(!p.startsWith('/console/')&&!['/state','/events'].includes(p))return route.continue();const body=req.method()==='GET'?null:req.postDataJSON();const id=body?.conversation||u.searchParams.get('conversation')||'console:main';
 if (p === "/console/coordination") return route.fulfill({ json: { enabled: false, nodes: [], events: [], epoch: 0, revision: 0, authoritative: false, observed_at: "", auto_failover: false, ready: false } });
 if(p==='/console/desktop')return route.fulfill({json:{enabled:false,setup_required:false,agent_count:0}});
 if(p==='/state')return route.fulfill({json:{at,hub:{node:'test',version:'test'},nodes:[],projects:[],agents:[],tasks:[],plans:[],attempts:[],landings:[]}});
 if(p==='/console/queue'){if(req.method()==='GET')f.queueReads++;if(req.method()==='POST'){f.post.push(body);assert.ok(['p','q','constructor','__proto__','restart','unavailable'].includes(f.bound[id]));let entry=f.queue.find(q=>q.key==='client:'+body.command_id);if(!entry){entry={id:'e'+f.queue.length,conversation:id,input:body.input,refs:body.refs,locale:body.locale,key:'client:'+body.command_id,state:'queued',enqueued_at:at};f.queue.push(entry);}if(f.reset){f.reset=false;return route.abort('connectionreset');}return route.fulfill({json:entry});}return route.fulfill({json:{queue:f.hideQueue?[]:f.queue.filter(q=>q.conversation===id),submission_keys:true,material_refs:true,interactive_requests:false}});}
 if(p==='/console/replies'){f.replyReads++;return route.fulfill({json:{enabled:true,replies:f.replies[id]||[]}});}
 if(p==='/console/context'){const origin=id.startsWith('console:origin-'),local={id:'local-kimi',node:'test',harness:'kimi',ready:true,usable:f.originUsable},remote={id:'remote-default',node:'remote',harness:'kimi',ready:true,usable:false};return route.fulfill({json:{enabled:true,context:{conversation:id,project:{id:origin?id.slice('console:origin-'.length):f.bound[id]||'home',node:'test',bound:origin||!!f.bound[id]},agent:origin||f.selected[id]==='local-kimi'?local:remote,agents:[local,remote]}}});}
 if(p==='/console/send'){if(body.input.startsWith('/use ')){f.agentSelect.push(body);f.selected[id]=body.input.slice('/use '.length);if(f.resetAgent){f.resetAgent=false;return route.abort('connectionreset');}return route.fulfill({json:{reply:{id:'select',conversation:id,kind:'reply',at,text:'Selected'}}});}f.send.push(body);if(body.input.startsWith('/project use ')){await f.bindGate.promise;f.bound[id]=body.input.slice('/project use '.length);if(f.resetBinding){f.resetBinding=false;return route.abort('connectionreset');}}return route.fulfill({json:{reply:{id:'control',conversation:id,kind:'reply',at,text:'Bound'}}});}
 f.errors.push(p);return route.fulfill({status:500,json:{error:'Unmocked'}});
});
async function waitFor(predicate,label){for(let i=0;i<100;i++){if(await predicate())return;await new Promise(r=>setTimeout(r,20));}assert.fail(label);}
const panel=()=>page.locator('[data-side-chat]');const textbox=()=>panel().getByRole('textbox',{name:/Side chat message|侧聊消息/});
try{
 await page.goto(url+'__side-harness.html');await page.getByRole('textbox',{name:'Main draft'}).fill('Keep main draft');await page.getByRole('button',{name:'Open A',exact:true}).click();await textbox().waitFor();assert.equal(f.send.length+f.post.length,0,'Opening a side chat cannot send an instruction or bind a project');await page.evaluate(()=>{const key='steve.console.drafts',draft=JSON.parse(localStorage.getItem(key));draft.quotes=[{conversation:'console:main',reply_id:'reply-main'}];localStorage.setItem(key,JSON.stringify(draft));});await textbox().fill('Side question');await page.getByRole('button',{name:'Add B',exact:true}).click();assert.equal(await textbox().inputValue(),'Side question');await waitFor(async()=>await panel().getByRole('listitem').count()===2,'additional selection is durably attached');assert.equal(await page.getByRole('textbox',{name:'Main draft'}).inputValue(),'Keep main draft');console.log('PASS opening and extending selection preserves independent drafts without sending');
 await page.getByRole('button',{name:'Move to review',exact:true}).click();await textbox().waitFor();assert.equal(await textbox().inputValue(),'Side question');await panel().getByRole('button',{name:'Send',exact:true}).click();await waitFor(()=>f.send.length===1,'binding starts on first explicit send');assert.equal(f.post.length,0);assert.equal(f.send[0].input,'/project use p');const sideID=f.send[0].conversation;assert.notEqual(sideID,'console:main');assert.equal(await page.evaluate(()=>sessionStorage.getItem('steve.conversation')),'console:main');await page.getByRole('button',{name:'Return to console host',exact:true}).click();await textbox().waitFor();assert.equal(await panel().getByRole('button',{name:'Send',exact:true}).isDisabled(),true);f.bindGate.release();await panel().getByRole('button',{name:'Retry this submission',exact:true}).waitFor();assert.equal(f.post.length,1);assert.equal(f.post[0].refs.length,2);assert.equal(f.agentSelect[0].input,'/use local-kimi');assert.equal(f.selected[sideID],'local-kimi','side chat inherits the source local agent instead of its incompatible remote default');assert.equal(f.post[0].quotes?.length||0,0,'side submission must not consume main conversation quotes');console.log('PASS first send binds once and survives a review-to-console surface remount');
 await textbox().fill('Next draft remains');await page.getByRole('button',{name:'Chinese',exact:true}).click();await panel().getByRole('button',{name:'重试这次发送',exact:true}).click();await waitFor(()=>f.post.length===2,'explicit retry');assert.equal(f.send.length,1,'A previously bound side conversation must not be rebound');assert.equal(f.post[1].command_id,f.post[0].command_id);assert.deepEqual(f.post[1].refs,f.post[0].refs);assert.equal(f.post[1].locale,'en');assert.equal(f.queue.length,1);assert.equal(await textbox().inputValue(),'Next draft remains');assert.equal(await page.getByRole('textbox',{name:'Main draft'}).inputValue(),'Keep main draft');
 await page.clock.install();
 await page.clock.runFor(500);
 const readsBeforeProgress={replies:f.replyReads,queue:f.queueReads};
 for(let index=0;index<12;index++) {
  await page.evaluate(e=>window.emit(e),{kind:'console.progress',conversation:sideID,at,progress:{answer:'Side progress '+index}});
  await page.clock.runFor(100);
 }
 assert.deepEqual({replies:f.replyReads,queue:f.queueReads},readsBeforeProgress,'Side progress must not refetch the full transcript and queue per chunk');
 await panel().getByText('Side progress 11',{exact:true}).waitFor();assert.equal(await panel().getByText('Side progress 10',{exact:true}).count(),0,'The live view shows the latest progress snapshot once');
 console.log('PASS side progress avoids per-chunk transcript and queue reads and streams the latest answer');
 f.hideQueue=false;f.queue[0].state='done';f.replies[sideID]=[{id:'r-side',kind:'reply',conversation:sideID,at,text:'Independent side response',format:'text'}];await page.evaluate(e=>window.emit(e),{kind:'console.reply',conversation:sideID,at});await panel().getByText('Independent side response',{exact:true}).waitFor();assert.equal(await panel().getByText('Side progress 11',{exact:true}).count(),0,'The reply replaces the live view');assert.equal(await page.getByText('Original conversation response',{exact:true}).isVisible(),true);assert.ok(f.replyReads>readsBeforeProgress.replies&&f.queueReads>readsBeforeProgress.queue,'A terminal side reply must still refresh transcript and queue');await page.clock.resume();console.log('PASS independent response and immutable-key retry do not replace the original chat');
 await page.getByRole('button',{name:'Open Q',exact:true}).click();await panel().getByText('q · material-q',{exact:true}).waitFor();assert.equal(await textbox().inputValue(),'');await textbox().fill('Other project question');f.resetBinding=true;await panel().getByRole('button',{name:'发送',exact:true}).click();await panel().getByRole('button',{name:'重试这次发送',exact:true}).waitFor();assert.equal(f.post.length,2,'Unconfirmed binding cannot send the model question');const binding=f.send.at(-1);await textbox().fill('Other project draft');await page.getByRole('button',{name:'English',exact:true}).click();await panel().getByRole('button',{name:'Retry this submission',exact:true}).click();await waitFor(()=>f.post.length===3,'binding retry then model question');assert.equal(f.send.at(-1).command_id,binding.command_id);assert.equal(f.send.at(-1).locale,binding.locale);assert.equal(f.post.at(-1).locale,'zh');assert.equal(await textbox().inputValue(),'Other project draft');await page.getByRole('button',{name:'Open A',exact:true}).click();await panel().getByText('p · material-a',{exact:true}).waitFor();assert.equal(await textbox().inputValue(),'Next draft remains');assert.equal(f.post.length,3);await panel().getByRole('button',{name:'Close side chat',exact:true}).click();await page.getByRole('button',{name:'Open A',exact:true}).click();await panel().getByText('p · material-a',{exact:true}).waitFor();assert.equal(await textbox().inputValue(),'Next draft remains');assert.equal(await page.evaluate(()=>sessionStorage.getItem('steve.conversation')),'console:main');console.log('PASS binding failures retry the original identity and locale without losing refs');console.log('PASS project-specific side sessions and close/reopen retain all drafts');
 for(const project of ['constructor','__proto__']) {
  const beforeWrites=f.send.length+f.post.length;
  await page.getByRole('button',{name:'Open '+project,exact:true}).click();await panel().getByText(project+' · material-'+(project==='__proto__'?'proto':'constructor'),{exact:true}).waitFor();await textbox().waitFor();
  const stored=await page.evaluate(project=>{const sessions=JSON.parse(localStorage.getItem('steve.side-conversations'));const drafts=JSON.parse(localStorage.getItem('steve.console.drafts'));return{owned:Object.hasOwn(sessions,project),session:sessions[project],refs:drafts.materials[sessions[project]?.id],undefinedRefs:drafts.materials.undefined}},project);
  assert.equal(stored.owned,true);assert.match(stored.session.id,/^console:side-/);assert.equal(stored.session.project,project);assert.equal(stored.refs.length,1);assert.equal(stored.refs[0].project,project);assert.equal(stored.undefinedRefs,undefined);
  assert.equal(f.send.length+f.post.length,beforeWrites,'Opening a prototype-named project must not send');
  await textbox().fill('Question for '+project);await panel().getByRole('button',{name:'Close side chat',exact:true}).click();await page.getByRole('button',{name:'Open '+project,exact:true}).click();await panel().getByText(project+' · material-'+(project==='__proto__'?'proto':'constructor'),{exact:true}).waitFor();await textbox().waitFor();
  assert.equal(await textbox().inputValue(),'Question for '+project);assert.equal(await page.evaluate(project=>JSON.parse(localStorage.getItem('steve.side-conversations'))[project].id,project),stored.session.id);
  const posts=f.post.length;await panel().getByRole('button',{name:'Send',exact:true}).click();await waitFor(()=>f.post.length===posts+1,'prototype project sends after a valid binding');
  assert.equal(f.send.at(-1).input,'/project use '+project);assert.equal(f.post.at(-1).conversation,stored.session.id);assert.equal(f.post.at(-1).refs.length,1);assert.equal(await page.getByRole('textbox',{name:'Main draft'}).inputValue(),'Keep main draft');
 }
 console.log('PASS prototype-named projects create, reopen and bind valid isolated side conversations');
 const writesBeforeRestart=f.send.length+f.post.length;
 await page.getByRole('button',{name:'Open restart',exact:true}).click();await panel().getByText('restart · material-restart',{exact:true}).waitFor();await textbox().fill('Unsent side draft survives full restart');
 await page.waitForFunction(()=>Object.values(JSON.parse(localStorage.getItem('steve.console.drafts')).drafts).includes('Unsent side draft survives full restart'));
 const unboundID=await page.evaluate(()=>JSON.parse(localStorage.getItem('steve.side-conversations')).restart.id);
 await page.close();page=await context.newPage();page.setDefaultTimeout(7000);page.on('pageerror',e=>f.errors.push(String(e)));await page.goto(url+'__side-harness.html');await page.getByRole('button',{name:'Open restart',exact:true}).click();await panel().getByText('restart · material-restart',{exact:true}).waitFor();
 assert.equal(await textbox().inputValue(),'Unsent side draft survives full restart');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('steve.side-conversations')).restart.id),unboundID);assert.equal(await panel().getByRole('listitem').count(),1);assert.equal(f.send.length+f.post.length,writesBeforeRestart);
 console.log('PASS a never-submitted side conversation retains a discoverable identity and draft after every page closes');
 const postsBeforeSelection=f.post.length;f.resetAgent=true;await panel().getByRole('button',{name:'Send',exact:true}).click();await panel().getByRole('button',{name:'Retry this submission',exact:true}).waitFor();assert.equal(f.post.length,postsBeforeSelection,'an unconfirmed agent selection cannot send the question');const agentControl=f.agentSelect.at(-1);const bindingControl=f.send.at(-1);
 await panel().getByRole('button',{name:'Retry this submission',exact:true}).click();await waitFor(()=>f.post.length===postsBeforeSelection+1,'confirmed inherited agent permits the original question');assert.equal(f.agentSelect.at(-1).command_id,agentControl.command_id);assert.equal(f.agentSelect.at(-1).input,agentControl.input);assert.equal(f.agentSelect.at(-1).locale,agentControl.locale);assert.equal(f.send.at(-1).command_id,bindingControl.command_id);
 console.log('PASS lost agent-selection response retries its original control identity before sending the question');
 f.originUsable=false;await page.getByRole('button',{name:'Open unavailable',exact:true}).click();await panel().getByText('unavailable · material-unavailable',{exact:true}).waitFor();const selectsBeforeUnavailable=f.agentSelect.length;await textbox().fill('Wait for an available agent');await panel().getByRole('button',{name:'Send',exact:true}).click();await panel().getByRole('button',{name:'Verify workbench selection',exact:true}).waitFor();assert.equal(f.post.length,postsBeforeSelection+1);assert.equal(f.agentSelect.length,selectsBeforeUnavailable,'unusable source agent is not selected');await waitFor(async()=>await textbox().inputValue()==='Wait for an available agent','agent unavailability retains the unsent draft');assert.equal(await panel().getByRole('link',{name:'Open in workbench',exact:true}).isVisible(),true);
 await panel().getByRole('button',{name:'Verify workbench selection',exact:true}).click();assert.equal(f.post.length,postsBeforeSelection+1);f.originUsable=true;const recoverySideID=await page.evaluate(()=>JSON.parse(localStorage.getItem('steve.side-conversations')).unavailable.id);f.selected[recoverySideID]='local-kimi';await panel().getByRole('button',{name:'Verify workbench selection',exact:true}).click();await panel().getByRole('button',{name:'Verify workbench selection',exact:true}).waitFor({state:'hidden'});await panel().getByRole('button',{name:'Send',exact:true}).click();await waitFor(()=>f.post.length===postsBeforeSelection+2,'explicit workbench selection resumes the preserved draft');
 console.log('PASS unavailable agents expose a workbench recovery path and never silently use the incompatible default');
 assert.deepEqual(f.errors,[]);
}catch(error){console.log('DEBUG',f.errors,await page.locator('body').innerText());throw error;}finally{f.bindGate.release();await context.close();await browser.close();await server.close();}
